package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Dev'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("Dev")
    name = "Dev"
    url = "https://github.com/MoWerr/vhserver"
    branch = "dev"
    userForTags = "MoWer"
    authMethod = password {
        userName = "MoWerr"
        password = "credentialsJSON:c936cbbd-a1d6-4a1d-87c0-48f933779af3"
    }
    param("oauthProviderId", "PROJECT_EXT_2")
}))

